### PR TITLE
[EC 86] GC.Collect should not be called

### LINKED ISSUE #36: [EC 86] GC.Collect should not be called
Hi all, on @Djoums advice, I suggest to add this rule.
Sonar already implements this rule, see it here : https://cloud-ci.sgs.com/sonar/coding_rules?open=csharpsquid%3AS1215&rule_key=csharpsquid%3AS1215

**Category : Performance**
**Severity : Warning**

## Why is this an issue
GC.Collect() is a method, often unecessary that could affect performances. It will trigger a blocking operation that will analyze every objects that are in memory in order to execute the cleanup.

## When can it be ignored ?

- If the specified generation is 0, in this case it should be harmless
- If a special event in your program caused a lot of long-lived objects to die

## Non-compliant Code Example
 ```C#
public static void Main()
{
    GC.Collect() // Non-compliant
}

public static void Main()
{
    GC.Collect(generation: 10) // Non-compliant
}
```
## Compliant Code Example
 ```C#
public static void Main()
{
    GC.Collect(generation: 0); // Compliant
}
```

### PR DESCRIPTION
**Pull request by GregoireBo**
Closes #36 

If you see any way to improve this part, please let me know
```C#
invocationExpression.Expression.GetText().ToString().Contains("GC.Collect")
```

### CODE REVIEW

**Comment by Djoums** [comment]
I'm not sure your code would work if you tried to call a fully qualified "System.GC.Collect()", and you rely a lot on strings.

IMO it'd be better like this, although I don't know if unordered arguments (with explicit naming) would mess the position of the generation parameter in the analyzer.

```csharp
if (context.SemanticModel.GetSymbolInfo(invocationExpression).Symbol is not IMethodSymbol methodSymbol ||
    methodSymbol.Name != nameof(GC.Collect) ||
    !SymbolEqualityComparer.Default.Equals(methodSymbol.ContainingType,
        context.SemanticModel.Compilation.GetTypeByMetadataName("System.GC")))
{
    return;
}

bool report = invocationExpression.ArgumentList.Arguments.Count == 0;
if (!report)
{
    var firstArgument = invocationExpression.ArgumentList.Arguments[0].Expression;
    var constantValue = context.SemanticModel.GetConstantValue(firstArgument);
    if (constantValue.Value is not int intValue || intValue != 0)
        report = true;
}

if (report)
    context.ReportDiagnostic(Diagnostic.Create(Descriptor, invocationExpression.GetLocation()));
```

**Comment by GregoireBo** [comment]
My code should work with System.GC.Collect also but your's more clean, I will look to integrate it. I will also look to merge the code from main and set the classes in .Core.
Thanks for your feedback !

**Comment by GregoireBo** [comment]
Hi @Djoums , refactored the code to implement you suggestions that will be more precise.
I confirm you that explicit naming will not be fetch by this code. I didn't find any solution RN to get the members by it's name instead of it's position.
Otherwise, as generation is the only argument typed with int could we fetch the argument that is of type int ?

**Comment by Djoums** [comment]
Hi @GregoireBo 
I looked into it and this is something we can do with Roslyn, check the following code snippet

```csharp
var firstArgument = invocationExpression.ArgumentList.Arguments[0];
if (firstArgument.NameColon is not null) // Named argument, may not be the one we want
{
	var firstParameterName = methodSymbol.Parameters[0].Name; // Parameter name from the method signature
	if (firstArgument.NameColon.Name.Identifier.Text != firstParameterName)
	{
		firstArgument = invocationExpression.ArgumentList.Arguments
			.First(arg => arg.NameColon?.Name.Identifier.Text == firstParameterName);
	}
}
```

**Comment by GregoireBo** [comment]
Hi @Djoums your suggestion is working pretty well, it now fetch the named parameters

**Comment by Djoums** [comment]
I'm still waiting for the approval on the main repo, but it's fine to commit the PR. Thanks for the contribution !

**Review by Djoums — APPROVED** [review]

**Comment by GregoireBo** [comment]
Thanks for your advices !

**Pull request merged**
